name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: Print greeting
       run: |
            echo "Hellow world1"
            echo "Hellow world2"
     - name: Print goodbye
       run: echo "done bye!"
